site_name: toapi
site_description: Turn any website into a JSON API.
site_author: Elliot Gao
site_url: https://elliotgao2.github.io/toapi/

repo_url: https://github.com/elliotgao2/toapi
repo_name: elliotgao2/toapi

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Topics:
      - Api: topics/api.md
      - Item: topics/item.md
      - Selectors: topics/selector.md
  - About:
      - Installation: about/installation.md
      - Release Notes: about/release-notes.md
      - Contributing: about/contributing.md
      - License: about/license.md

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

copyright: Copyright &copy; 2021-2026 Elliot Gao
